services:
  backend-in-every-lang-php:
    container_name: backend-in-every-lang-php
    build:
      dockerfile: Dockerfile
      context: .
    image: backend-in-every-lang-php:latest
    ports:
      - "9997:9997"
    volumes:
      - "./database.db:/app/database.db"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "9997"
      DB_PATH: "/app/database.db"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:$${APP_PORT}/healthcheck || exit 1" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - default
networks:
  default:
    driver: bridge